global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: "prometheus"
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: "WinServer22025"
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: [100.90.193.93:9182]
  metric_relabel_configs:
    - source_labels: [instance]
      target_label: instance
      regex: '(.*)'
      replacement: 'winserver2025'
- job_name: "MacOS"
  scheme: http
  static_configs:
    - targets: [192.168.50.65:9100]
- job_name: "proxmox"
  scheme: http
  static_configs:
    - targets: [192.168.50.199:9100]
